# Generated by Django 3.2.5 on 2021-07-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miSitio', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
