# Generated by Django 3.2.5 on 2021-07-07 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miSitio', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'productos'},
        ),
    ]
