# Generated by Django 3.2.5 on 2021-07-07 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miSitio', '0007_auto_20210707_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('titulo', models.CharField(max_length=64)),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.CharField(max_length=180)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=64)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='miSitio.categoria')),
            ],
            options={
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='lista_productos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='miSitio.Producto'),
        ),
    ]
