# Generated by Django 3.2.5 on 2021-07-07 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miSitio', '0008_auto_20210707_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='price',
        ),
    ]
